"""empty message

Revision ID: 7590f6a4eaf3
Revises: 06980db83581
Create Date: 2021-08-26 00:03:19.120909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7590f6a4eaf3'
down_revision = '06980db83581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('checkin', sa.DateTime(), nullable=True),
    sa.Column('checkout', sa.DateTime(), nullable=True),
    sa.Column('confirmation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
